### ISSUE TITLE
Hub Federation (hub-side)

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/herald.go#6]
The goal of hub federation is to allow clients to find out about hubs they don't know about.

- [x] hub stores it's list of known peers (other hubs) on disk. list starts empty if no hubs are known
- [x] on startup, load saved peers from disk
- [x] add grpc endpoint that adds a peer to the list of known peers (and stores it to disk). if the peer is new, the hub also announces itself to the peer so the peer knows about it
- [x] on startup, hub should announce itself to all known peers
- [x] add config to disable federation. if set, the peer-adding rpc does nothing and the hub does not announce itself to other peers. but the starting list of seed hubs still lets it know about other hubs.
- [x] figure out how connecting to other hubs and staying connected works. 

**do not allow non-LBRY-Inc hubs to peer with us until claim proofs are re-enabled (#2183)**. this prolly means having federation disabled on hubs by default.

## questions
- does any of the python code need to be brought to Go? (e.g. peer manager, udp announcement)
- should hubs prune their peer list? how do they detect peers that are offline, peers that are fake, etc?
- should hubs validate peers somehow?

**Comment by lyoshenka** [comment]
Victor will have the first two checkboxes done before standup on Wednesday

**Comment by lyoshenka** [comment]
The last day to do **anything** on this is July 30th. After that we're merging whatever's done and switching issues.

**Comment by lyoshenka** [comment]
victor didn't do much on this and now he's working with jack to finish the leveldb/reorg work

**Comment by lothropgauss** [comment]
https://github.com/lbryio/herald.go/pull/24
